version: '3'
services:
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_PASSWORD: test_pass
            # MYSQL_ROOT_HOST: 0.0.0.0:3306
        # command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        networks:
            - web-db-net
    # web:
    #     build:
    #         context: .
    #         dockerfile: docker/apache/Dockerfile
    #         args:
    #             uid: ${UID}
    #     environment:
    #         - APACHE_RUN_USER=#${UID}
    #         - APACHE_RUN_GROUP=#${UID}
    #     restart: unless-stopped
    #     volumes: 
    #         - ./:/var/www/html
    #         - ./apache_log:/var/log/apache2
    #     ports:
    #         - 8080:80
    #     depends_on: 
    #         - db
    #     links:
    #         - db
    #     networks:
    #         - web-db-net
networks:
    web-db-net:
        driver: bridge
